# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PJNetwork' do
    
  pod 'PJNetwork', :path => '../'
  
  
  ### Remote ###
  pod 'MJExtension'

end
